### PR TITLE
Jeremy

### PR DESCRIPTION
**Pull request by magland**

### CODE REVIEW

**Comment by colehurwitz31** [comment]
Was this the issues with the Mountainsort memory leak I ran into?

**Comment by magland** [comment]
Yes, I believe so.

**Comment by colehurwitz31** [comment]
Great! If we merge that today, I can rerun on the raw data set tomorrow. Thanks!

**Comment by colehurwitz31** [comment]
I am gonna merge this so I can keep working on the experiments

**Pull request merged**
